### ISSUE TITLE
optimize render reflows

### ISSUE THREAD

**Issue by jantimon** [Snugug/eq.js#1]
As I have written in twitter before there is a huge performance issue if you mix dom read and write statements.

I wrote a quick fix to demonstrate possible performance gains:  
[source code](https://github.com/jantimon/eq.js/blob/master/build/eq.js)

To the the differences go to the following examples, open your developer toolbar and resize the browser.
[Modified version](http://jantimon.github.io/eq.js/index.html)

Dom update: 15.518ms 

[Original version](http://jantimon.github.io/eq.js/index.reflow.html)

Dom update: 1547.678ms

**Comment by Snugug** [comment]
Ahh, I understand the difference with what you're doing now. Please issue a PR so I can bring it in!
