### ISSUE TITLE
Update CONTRIBUTING with instructions for creating dist files

### ISSUE THREAD

**Issue by rupl** [Snugug/eq.js#10]
I wanted to provide a PR that updates the library but didn't know the process for updating the files in the `dist` directory.

**Comment by Snugug** [comment]
Read the damn [Gruntfile](https://github.com/Snugug/eq.js/blob/1.x.x/Gruntfile.js)! Either `grunt server` to work on the project, or `grunt build` to build the dist versions.

**Comment by rupl** [comment]
Snuggy, don't be mean to me!

**Comment by Snugug** [comment]
Aww, I <3 you rupl
