### ISSUE TITLE
Allow nodeList to be passed into callback during eqjs.query()

### ISSUE THREAD

**Issue by rupl** [Snugug/eq.js#14]
The `query` method takes a nodeList argument that allows it to reduce the scope of its processing. It also accepts a callback, and I think it would be super-useful to pass the nodeList along to the callback to allow for direct processing of the DOM elements that were affected.

**Comment by rupl** [comment]
I think commit 568674d fixes this issue, correct?

**Comment by Snugug** [comment]
Yah, I believe so.
