### ISSUE TITLE
multiple states in eq sass mixin failing

### ISSUE THREAD

**Issue by VinSpee** [Snugug/eq.js#20]
Great work on eq.js. I'm using it along side of the sass extension, which works great until I need to include multiple states.

```
+eq('medium', 'large')
```

produces

> Syntax error: Mixin eq takes 1 argument but 2 were passed.

any ideas on why this isn't working?

Thanks!

**Comment by Snugug** [comment]
What version are you using? Previous versions only supported one argument

**Comment by VinSpee** [comment]
the latest release. my `bower.json`:

```
    "eq.js": "~1.4.1",
```

**Comment by VinSpee** [comment]
ahh I see that there hasn't been a release since that was added. any reason?
