### ISSUE TITLE
Add Scott Jehl technique

### ISSUE THREAD

**Issue by Snugug** [Snugug/eq.js#22]
@scottjehl came up with a [CSS encapsulated](http://jsbin.com/ramiguzefiji/1/edit) technique for element queries. Look into what it would take to add it.

**Comment by Snugug** [comment]
http://sassmeister.com/gist/a5400d9ba809df176506

**Comment by scottjehl** [comment]
Nice little pattern. You folks sure are quick with the Sass examples. 

So, just so I'm clear, your script would need some modifications to wire this up too right?

**Comment by Snugug** [comment]
Yes, it would need some modification to be able to support both, but I think it's do-able.

**Comment by Snugug** [comment]
Mostly I think it would need to be modified to grab the correct selectors from the HTML content and grab sizes from the :before, but the rest of the script should work more or less fine once those things were handled.

**Comment by Snugug** [comment]
FWIW, my assumption is exactly what wound up needing to happen; pretty straight forward once those two things were added. Needed to add a `load` event too.
