### ISSUE TITLE
No easy way to target root state with css

### ISSUE THREAD

**Issue by micahgodbolt** [Snugug/eq.js#23]
I'd like to style only the lowest eq state (before any of my breakpoints kick in). I had to do this convoluted approach 

`.popular-video:not([data-eq-state]) .popular-video-img-container`

Would it be possible to always print data-eq-state, but have the value be blank or some default value, so that we could target it?

`[data-eq-state=""] .popular-video-img-container`

This is much more preferable than setting base styles and then overwriting them on the larger states.

**Comment by Snugug** [comment]
I… think you may be using it wrong then?

Think of element queries just like you would media queries; you start with the base set of styling, then tweak when you need to.

**Comment by micahgodbolt** [comment]
I just want to be able to target that first max-width media query. As I said, I can do it with a :not([data-eq-state]) but that is kinda kludgy, and I have to specify the parent class that would/wouldn't have that data attr.

**Comment by Snugug** [comment]
I assume you mean `min-width`?

IMO you'd want to target that parent selector anyway; simply having `[data-eq-state]` could potentially match much further up the tree than you would want (say if you have elements nested inside each other).  As `:not` doesn't add any specificity, and `eq.js` removes the state if there isn't one available, I think that `.parent:not([data-eq-state])` is a more elegant (and equal specificity) solution to `.parent[data-eq-state=""]`

**Comment by micahgodbolt** [comment]
Ok i'm an idiot. I was telling a friend about this "problem" when I realized the obvious solution.

data-eq-pts="small: 0, large: 500"

Now I have a 0-499 and a 500+
