### ISSUE TITLE
eq.js breaks when there is an iframe on the page

### ISSUE THREAD

**Issue by a-fro** [Snugug/eq.js#24]
To reproduce, simply add an iframe to your sample index.html page.

**Comment by Snugug** [comment]
Please provide me with some more information about what breaks and where it breaks. Is there an error thrown? What browsers/OSes are you seeing this on? Does it break with any other tags?

**Comment by a-fro** [comment]
Sorry, my mistake. I thought you could use self-closing tags with iframes. Once I close the tag, it works.
