### ISSUE TITLE
getComputedStyle not working in IE8

### ISSUE THREAD

**Issue by thasmo** [Snugug/eq.js#29]
On line 94 eq.js uses `getComputedStyle` which doesn't exist in IE8 and I haven't seen any mention about it in the docs. Do we need to supply a polyfill for that function for IE8 or is it a bug?

**Comment by thasmo** [comment]
There's also a `forEach` on line 246, which doesn't work for me in IE8. Should eq.js work in IE8 or isn't it supported anymore?

**Comment by thasmo** [comment]
Ah, I saw those two function calls were introduced 8 days ago and have been released with version 1.5. Is there a chance to have 1.5 work with IE8?

**Comment by Snugug** [comment]
Whoops, I totally didn't think of IE8 when I wrote the CSS stuff. I need to fix that.
