### ISSUE TITLE
Replace single attr of JSON with multiple attrs

### ISSUE THREAD

**Issue by rupl** [Snugug/eq.js#3]
The well-formatted JSON thing makes this a no-go in lots of frameworks whose logic has hardcoded double-quotes for attribute values.

I think it's more compatible with most web frameworks to put multiple attributes on an element, each corresponding to one element breakpoint. I realize this slows down the parsing and initialization, but that didn't seem to be the slow thing when we did the initial round of testing. Also it'll be usable for more people and you can take that gigantic warning out of the README.

Sample markup:

``` html
<div class="component" data-eq-small="400" data-eq-medium="600" data-eq-large="900">
  <h1>Hello World</h1>
</div>
```

The other syntax I thought of is a little riskier because it relies on the order of the values to create correlation between breakpoint labels and values:

``` html
<div class="component" data-eq-labels="small,medium,large" data-eq-vals="400,600,900">
  <h1>Hello World</h1>
</div>
```

Either way, the non-JSON is simpler to render and is not subject to the fragile syntax-checking that JSON imposes.

**Comment by Snugug** [comment]
I'd prefer to keep it all as one attribute, but agree that well formatted JSON is probably a non-starter for a lot of projects. What about something like the following:

``` html
<div data-eq-pts="small: 500, medium: 600, large: 900">
  Hello World
</div>
```

The sample code I've written to parse this also is very forgiving of whitespace (spaces after : and , are optional)

**Comment by rupl** [comment]
I dig it. That syntax is easier to generate and I can see how having one hardcoded attribute makes the parser more reliable/quick.

**Comment by Snugug** [comment]
Sounds good, will update the parser.

Last thing needed before a 1.0 is having a way to call a one-off compile.

**Comment by Snugug** [comment]
How critical is it that we use `data-`? I know it's technically invalid HTML if we don't, but many JavaScript frameworks (most notable Angular) use custom attributes. BTW. I have this working in the [animation branch](https://github.com/Snugug/eq.js/tree/animation)

**Comment by Snugug** [comment]
I'll roll with `data-`.
