### ISSUE TITLE
Installation issues with Bower/compass.

### ISSUE THREAD

**Issue by phi0x** [Snugug/eq.js#32]
Hi there, thanks for the great project! However when I'm trying to install eq.js into my project, I'm having the following issues:
I use compass and bower, compass is complaining that in my scss file '@import 'eq';' is not found.

I've used bower to install eq.js which it states is installed, I've added the appropriate line to config.rb as well as noted in the documentation. How do I get the @import 'eq'; to work with compass?

Compass shows that it loads everything fine for bower.

Your instructions page also notes something about adding eq.js to the HTML, how do we do that? I can't see linking a eq.js file in the HTML being the answer as compass does not read the HTML files to process the @import 'eq'; line.

If you can clarify how to get eq.js working with compass that would be greatly appreciated. Thanks.

**Comment by phi0x** [comment]
Figured it out, have not used bower much in the past. had to run the bower install -g eq.js --save command from within the project folder so that the bower_components folder would be created within the project folder itself. Then when adding the arguments to config.rb it found the bower_components folder within the project. Maybe just update the readme to let people that don't know much about bower yet.

**Comment by Snugug** [comment]
You should not need to install it globally (the `-g` flag); simply running `bower install eq.js` will install it to your project's `bower_components` folder (which can change from project to project, but is the default and should be created if it's not already there).

In regards to using the Sass file, you cannot simply `@import 'eq';`; you either need to add the import path to Compass as [described in the README](https://github.com/Snugug/eq.js#bonus) or import the full relative path from your Sass file, so if your file is `project-root/sass/style.scss`, in that file you'd do `@import '../bower_components/bower_components/eq.js/sass/eq'`
