### ISSUE TITLE
Calling eqjs.query throws error

### ISSUE THREAD

**Issue by thasmo** [Snugug/eq.js#33]
When calling `eqjs.query($('ul.tabs').toArray())` I get the error `TypeError: next is undefined` on line 165. I'm using version 1.6.0.

**Comment by Snugug** [comment]
Can you provide a reduced example that includes some HTML? And can you try [`document.querySelectorAll()`](http://caniuse.com/#search=querySelectorAll) instead of jQuery?

**Comment by thasmo** [comment]
Same error with `document.querySelectorAll()`. Does this maybe happen because I have only one breakpoint defined? The foreach runs only once but inside with `var next = eqPts[j + 1];` it tries to access `eqPts[1]`, which is not defined, as I have only one breakpoint.

**Comment by thasmo** [comment]
Hm, but that error should happen regardless of how many breakpoints are defined.

**Comment by Snugug** [comment]
If you only have one defined it should exit out before the loop. Do you have a reduced example that includes some HTML that I can look at?

**Comment by thasmo** [comment]
@Snugug, I was able to reproduce the problem on a test case:
http://jsfiddle.net/cw063yxp/

Thanks for your help!

**Comment by thasmo** [comment]
@Snugug, does the test-case help you to figure out what's going on?

**Comment by thasmo** [comment]
Wait, do I need to pass only DOM nodes which _have_ a `data-eq-pts` attribute, and not any parent nodes? I thought I can pass any DOM nodes and eq.js will parse the DOM fragment for relevant elements.

**Comment by Snugug** [comment]
Correct, you need to pass the nodes you want parsed, not any nodes.

**Comment by thasmo** [comment]
Alright, my mistake. Docs could be more specific, but anway, love the plugin! :)
