### ISSUE TITLE
Error compiling with Libsass

### ISSUE THREAD

**Issue by lmartins** [Snugug/eq.js#35]
Hey Sam,

Thank you for this brilliant library.
I have one issue with with when trying to use the mixins for Sass.

The following code triggers a compile error:

```
[10:48:31] gulp-notify: [Compile Error] Error in plugin 'gulp-sass'
Message:
    error reading values after ,
```

While the compiler doesn't point the offending code, i've managed to isolate this part:

```
@if not index($EQ-Selectors, &) {
    $EQ-Selectors: append($EQ-Selectors, &, 'comma') !global;
 }
```

Any tips for getting over this?

Thanks again.

**Comment by Snugug** [comment]
Unfortunately, nothing that I can do until sass/libsass#548 gets resolved.

Your other option is to just copy the `eq` mixin into your project, but that will prevent you from using the CSS style element queries.

**Comment by lmartins** [comment]
Thanks for the feedback, i'll keep an eye on that ticket then. 
Cheers.

**Comment by lmartins** [comment]
Hey Sam, 

I tested this again while testing gulp-sass v.2 and it still outputs the same error. 
I've checked the https://github.com/sass/libsass/issues/548 which is now marked as solved, should I report the issue still stands?

**Comment by Snugug** [comment]
It's resolved in 3.2, which is in alpha right now but not in a `node-sass` release

**Comment by P3anuts** [comment]
I am trying to run it now using grunt-sass which uses node-sass 3.1.2 which in turn uses libsass 3.2.4. Then I get this error:

> > invalid selector after &
> >   Line 53  Column 42  bower_components\eq.js\sass_eq.scss

Line 53 is this:  
$EQ-Selectors: append($EQ-Selectors, &, 'comma') !global;

Any ideas on how this can solved?

**Comment by filmic** [comment]
@P3anuts You can find a workaround for this issue in this pull request: https://github.com/Snugug/eq.js/pull/46

I also reported this bug in the libsass project: https://github.com/sass/libsass/issues/1260

**Comment by P3anuts** [comment]
@filmic Works great! Thanks a lot!
