### ISSUE TITLE
Post refresh event or callback?

### ISSUE THREAD

**Issue by lmartins** [Snugug/eq.js#40]
Im facing an issue I was hoping you could help me out.

I have a container that has different layouts according to the box state, this state is dictated by eq.js that, at some point, makes the container go from full width to a two column layout. In one of those columns I have a slider which also calculates the available size to trigger its behaviour.

![screen shot 2015-03-31 at 16 11 20](https://cloud.githubusercontent.com/assets/151981/6922138/f905c3b4-d7c0-11e4-95a5-1a369fd1f3b2.png)

I was thinking of attaching an event triggered by `eqjs.refreshNodes();` or having that function call a callback. This way when the nodes were updated by eq.js, I would have my slider recalculate it's properties also. 

Im not seeing a suitable event or callback in the source of eq.js, is this something you considered?

**Comment by Snugug** [comment]
`eqjs.refreshNodes()` refreshes the list of nodes, but doesn't query the elements. `eqjs.query()` does, and that accepts a callback. I've contemplated adding an event, but haven't done so yet.

**Comment by lmartins** [comment]
Hey Sam, thanks for the feedback.
An event would be really useful, I'll see if I can find a solution to get around my use case.
Thanks.
