### ISSUE TITLE
Libsass, error reading values after , on line 52

### ISSUE THREAD

**Issue by christianmagill** [Snugug/eq.js#45]
I get the following error compiling with libsass 3.2.2

bower_components/eq.js/sass/_eq.scss
  53:42  invalid selector after &

**Comment by lmartins** [comment]
Now that we have libsass so much closer to Ruby Sass, @Snugug Sam, do you think this is something we could have solved in the near future?

The affected line are the following:

``` sass
  @if not index($EQ-Selectors, &) {
    $EQ-Selectors: append($EQ-Selectors, &, 'comma') !global;
  }
```

**Comment by Snugug** [comment]
Bah! I wrote a test for them to fix this! I'll go and look
