### ISSUE TITLE
Nested responsive element has incorrect size

### ISSUE THREAD

**Issue by lolmaus** [Snugug/eq.js#47]
# Live Demo

http://lolmaus.github.io/loadimpact-assignment/#/requests

Steps to reproduce:
1. Open the page at 700px width
2. Click the "more options" link
3. See the options component aligned vertically, that's the small layout
4. The larger horizontal layout appears only after window resize

The options component is displayed/hidden via jQuery's `.slideUp()` and `.slideDown()`.

I expected to resolve this issue with `eqjs.refreshNodes()` but it does not help.
# Screenshot

[![Imgur](http://i.imgur.com/MLU4Iav.png)](http://i.imgur.com/MLU4Iav.png)

Note that the third red circle shows the width of the parent element (they both have the same width). The element in question has its width displayed as `auto`, maybe this has something to do with the issue.

**Comment by filmic** [comment]
Element queries work only on element that has layout (so its width can be calculated).

Your `<div class="paginatorWithOptions-options-inner">` element is hidden when page loads (its parent has `display: none` style) so it has no layout and the element query doesn't get applied.

You will have to detect the moment when the element becomes visible (maybe use jQuery callback when slidedown animation starts?) and then call `eqjs.query()` to recalculate the element query.

**Comment by lolmaus** [comment]
Ah, `eqjs.query()` does work, thank you!

I was sure that `eqjs.refreshNodes()` should also do the thing:

> Alternatively, you can use eqjs.refreshNodes() to update the listing of nodes that is use by eqjs.query() with **all of the nodes currently in the DOM**.
