### ISSUE TITLE
JS Error in IE

### ISSUE THREAD

**Issue by lmartins** [Snugug/eq.js#49]
Hi Sam,

Spotted a new problem in IE, most likely related to the introduction of the custom events.
The error only happens on IE, here's the message im getting:

```
SCRIPT445: Object doesn't support this action
File: eq.min.js, Line: 2, Column: 1508
```

That points to this line:

``` javascript
u = new CustomEvent("eqResize", { detail: a }), p.dispatchEvent(u);
```

Thanks.

**Comment by lmartins** [comment]
It seems that Internet Explorer doesn't support the constructor eq.js uses to build the custom events:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility

**Comment by Snugug** [comment]
Looks like you need to use the polyfilled version instead of the stand-alone version.

**Comment by Snugug** [comment]
~~Actually, looks like I forgot the Custom Event polyfill in the Polyfilled version.~~ [It's there](https://github.com/Snugug/eq.js/blob/1.x.x/tasks/dist.js#L56)

**Comment by lmartins** [comment]
Cool, thank you Sam.
