### ISSUE TITLE
Firing 'eqResize' event fails in IE11

### ISSUE THREAD

**Issue by filmic** [Snugug/eq.js#53]
Execution of line:
`eqResizeEvent = new CustomEvent('eqResize', {'detail': eqState});`

throws an error in IE11:
`SCRIPT445: Object doesn't support this action`

I use eq.polyfilled.min.js.

This is due the IE implementation of the CustomEvent - see https://github.com/sindresorhus/devtools-detect/issues/9#issuecomment-29647713

**Comment by filmic** [comment]
This caused by incorrect detection of CustomEvent feature support so the polyfill is not used in IE11.

The generated eq.polyfilled code has check:

```
if (!'CustomEvent' in window &&

        // In Safari, typeof CustomEvent == 'object' but it otherwise works fine
        (typeof window.CustomEvent === 'function' ||
            (window.CustomEvent.toString().indexOf('CustomEventConstructor') > -1))
    ) {//polyfill}
```

but it should be:

```
if (!('CustomEvent' in window &&

        // In Safari, typeof CustomEvent == 'object' but it otherwise works fine
        (typeof window.CustomEvent === 'function' ||
            (window.CustomEvent.toString().indexOf('CustomEventConstructor') > -1))
    )) {//polyfill}
```

**Comment by Snugug** [comment]
Merged. Releasing an update soon.

**Comment by lmartins** [comment]
Im using the latest build 1.7.1 and im still getting this error when IE tries do create the eqResize custom event, is this expected behaviour?

**Comment by lmartins** [comment]
Btw, the errors im getting happen in IE11, the message is as follows:

```
SCRIPT445: Object doesn't support this action
File: eq.min.js, Line: 2, Column: 1508
```

And that refers to:
`u = new CustomEvent("eqResize", { detail: a, bubbles: !0 })`

Maybe something's still wrong with the polyfill. When using another polyfill such as https://github.com/krambuhl/custom-event-polyfill it does work with any errors.

**Comment by Snugug** [comment]
Are you using the polyfilled version or not?

**Comment by lmartins** [comment]
So sorry Sam. Im using JSPM and for some reason my usual approach to override the entry point is failing in this case. So yeah, I was loading the non-polyfilled despite asking for it.
Thanks and sorry about that.

**Comment by jonscottclark** [comment]
Hey @Snugug, could you include a note about CustomEvent in the polyfills section in the readme?
