### ISSUE TITLE
Concatenate data attributes

### ISSUE THREAD

**Issue by starryeyez024** [Snugug/eq.js#6]
Awesome work! This is a life-saver. :)

One question about the <a href="https://github.com/Snugug/eq.js/blob/1.x.x/sass/_eq.scss">sass mixin</a>, which I realize is just a bonus and not totally necessary, but is there a way to use the mixin in such a way so that you may concatenate the data attributes?

For instance, if you had 3 data attributes set on a div, and you wanted to say, "if the eq is small, medium or large, add style x." Basically the equivalent of using a media query  that says "if the page reaches 500px _and up_."

If this is is the desired CSS:
.foo[data-eq-state="sm"],
.foo[data-eq-state="md"],
.foo[data-eq-state="lg"] {
  float: left;
  margin-right: 15px;
}

I could write Sass like this:
.foo
  &[data-eq-state="sm"],
  &[data-eq-state="md"],
  &[data-eq-state="lg"]
    float: left
    margin-right: 15px

but if I wanted to use the eq mixin, it fails as expected: 
.foo
  +eq("sm"),
  +eq("md"),
  +eq("lg")  
    float: left
    margin-right: 15px

Is it possible to write the mixin so you could target the eq "small and up"? Thanks!!

**Comment by Snugug** [comment]
Not yet, but I can add it

**Comment by Snugug** [comment]
I'm holding off on this until scripted selector issues get resolved in Sass 3.3 (probably rc3), otherwise this is going to be very weird to do.
