### ISSUE TITLE
use `eqResize` without using `data-eq-pts`?

### ISSUE THREAD

**Issue by FezVrasta** [Snugug/eq.js#64]
I'd like to listen for the `eqResize` event without add the `data-eq-pts` attribute.

Is there a way to manually enable the eq size listener on a given element from JS?

**Comment by FezVrasta** [comment]
Up?

**Comment by Snugug** [comment]
There are two ways of assigning element queries: data-eq-pts or through CSS. There is no pure JavaScript constructor.

**Comment by FezVrasta** [comment]
Any chance to get this feature?
