### ISSUE TITLE
Improvement request: add convinience method for eqjs.refreshNodes + eqjs.query 

### ISSUE THREAD

**Issue by leifoolsen** [Snugug/eq.js#72]
Thank you for a great library.

I use eq.js in a single page ES6 application. When I load a new page I call `eqjs.refreshNodes` and `eqjs.query` after rendering the new page fragment. It would be great to have a convenience method for this, for example. `eqjs.load ()`.

[edit: deleted. not an issue]
It does not seem that ES6 import working correctly, `import { eqjs } from 'eq.js'`, gives the following error message when I try to call a method: "Type Error: Can not read property 'refreshNodes' of undefined". If I use require, `const eqjs = require ('eq.js')`, everything works as expected.
[end deleted text]
Regards
Leif Olsen

**Comment by Snugug** [comment]
Please split this up in to two issues

**Comment by jonscottclark** [comment]
@leifoolsen When importing with ES6 simply use:

`import eqjs from 'eq.js'`

This imports the default export, which will bring its member functions with it, such as query(), refreshNodes(), etc. What you're trying to do is import a single member function of the default export.

**Comment by leifoolsen** [comment]
@jonscottclark Thank you for spotting that. It was a copy/paste fault of mine. After removing the curly braces, es.js indeed works with ES6 import.

**Comment by leifoolsen** [comment]
@Snugug Thank you for a great library. So far I have used eq.js to rewrite the Google Material Design Lite grid to use element queries, and have not experienced any problems in that process.

The import issue was not an issue at all, as @jonscottclark pointed out - so I just remove that from the heading text.
