### ISSUE TITLE
PLEASE update bower

### ISSUE THREAD

**Issue by FezVrasta** [Snugug/eq.js#73]
you have to update the bower release...

really, if you haven't time to maintain this project let us know, so someone can take ownership of it.

**Comment by Snugug** [comment]
Yo. You've got to stop.

You have now, in multiple issues, demanded that I abdicate maintainership if I'm unable to adhere to your needs. It's incredibly rude. I volunteer my time on this project. While I'm happy you've found it useful, I do not work for you.

Currently, besides this issue, there are 0 issues open related to bower version. There are a million ways you could have informed me that there was a version mismatch with Bower without being rude and demanding. If you continue to behave in this manner, I will proceed to close your issues without comment moving forward.
