### ISSUE TITLE
Reconsider usage of Object.getPrototypeOf

### ISSUE THREAD

**Issue by jtwalters** [Snugug/eq.js#8]
Is there a better way to rewrite the script without relying on Object.getPrototypeOf? If you're using a singleton pattern, you could instead follow an approach such as [Addy Osmani's Singleton Pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#singletonpatternjavascript).

**Comment by Snugug** [comment]
Is there an advantage to creating a singleton instead of simply polyfilling this?

**Comment by jtwalters** [comment]
I can't seem to come up with a "better way." The issue is related to the requestAnimationFrame callback functions needing the correct context when called. I was working on refactoring the code to avoid using `Object.getPrototypeOf`, however, maintaining IE8 compatibility would require another polyfill, `Function.prototype.bind` in my alternate solution.

Unless someone else chimes in, you can probably close this issue, since I can't describe a better approach.

**Comment by Snugug** [comment]
Yah, going to close this.
